function add() {
    let a = 1
    let b = 3
    let c = a / b
    console.log(a / b);
    console.log(y);
}
try {
    add();
}
catch (error)
{
    console.log('ann error occur')
    console.log('error meassage' + error)
}

finally {
    console.log("the error will be clreard")
}